#!/bin/bash
# Job script for hmat_107
# Generated by abacusflow
# Run this script from: /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/work_cal3/hmat_107

# ===== 环境初始化 =====
# 设置 OpenMP 线程数（避免超线程问题）
export OMP_NUM_THREADS=1

# 激活 conda 环境
source /XYFS01/nscc-gz_pinchen_1/sf_install/miniconda3/etc/profile.d/conda.sh
conda activate dftflow

# 加载必要的 module
# MODULES: intel/oneapi2023.2_noimpi mpi/mpich/4.1.2-icc-oneapi2023.2-ch4 elpa/2024.05.001-icc-oneapi2023.2-mpich-4.1.2-ch4
export MODULESHOME=/usr/share/modules
export MODULEPATH=/APP/u22/x86/modulepath/Compilers:/APP/u22/x86/modulepath/application
export MODULES_CMD=/usr/lib/x86_64-linux-gnu/modulecmd.tcl
ml() { module ml "$@"; }
module() { _module_raw "$@" 2>&1; }
_module_raw() { eval `/usr/bin/tclsh8.6 /usr/lib/x86_64-linux-gnu/modulecmd.tcl bash "$@"`; }

# 加载模块
for mod in intel/oneapi2023.2_noimpi mpi/mpich/4.1.2-icc-oneapi2023.2-ch4 elpa/2024.05.001-icc-oneapi2023.2-mpich-4.1.2-ch4; do
  module load $mod
done

# 确保在正确的目录
cd /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/work_cal3/hmat_107 || exit 1

echo '[...]TASK START!'
echo '[...]Structure: InputPoscar/hmat_107.poscar'
echo "[...]Working directory: $(pwd)"

# 复制结构文件到当前目录
if [ ! -f STRU.vasp ]; then
  cp /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/InputPoscar/hmat_107.poscar ./STRU.vasp
fi

# 初始化状态日志
stat_log=stat.log
> $stat_log

echo '[...]start Test_spin task'
if [ ! -d Test_spin ];then
  mkdir Test_spin && cd Test_spin || exit
else
  cd Test_spin
fi

echo '[...]prepare Test_spin inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Test_spin

# Create ignore.txt marker for Test_spin (ignore_error=True in workflow.json)
touch ignore.txt

for try_num in $(seq 0 1)
  do
  echo "[...]task Test_spin round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Test_spin/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Test_spin/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py spin --work_dir .
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 1 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Test_spin
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Test_spin failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Test_spin failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py spin --work_dir .
    echo 'Test_spin success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Test_spin job done!'
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py spin --work_dir .
  echo 'Test_spin success' >> ../stat.log
fi

cd ..

echo '[...]start Coarse_relax task'
if [ ! -d Coarse_relax ];then
  mkdir Coarse_relax && cd Coarse_relax || exit
else
  cd Coarse_relax
fi

echo '[...]prepare Coarse_relax inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Coarse_relax

# Create ignore.txt marker for Coarse_relax (ignore_error=True in workflow.json)
touch ignore.txt

for try_num in $(seq 0 1)
  do
  echo "[...]task Coarse_relax round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Coarse_relax/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Coarse_relax/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 1 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Coarse_relax
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Coarse_relax failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Coarse_relax failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    echo 'Coarse_relax success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Coarse_relax job done!'
  echo 'Coarse_relax success' >> ../stat.log
fi

cd ..

echo '[...]start Relax task'
if [ ! -d Relax ];then
  mkdir Relax && cd Relax || exit
else
  cd Relax
fi

echo '[...]prepare Relax inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Relax

# Create ignore.txt marker for Relax (ignore_error=True in workflow.json)
touch ignore.txt

for try_num in $(seq 0 2)
  do
  echo "[...]task Relax round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Relax/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Relax/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 2 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Relax
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Relax failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Relax failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    echo 'Relax success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Relax job done!'
  echo 'Relax success' >> ../stat.log
fi

cd ..

echo '[...]start Scf task'
if [ ! -d Scf ];then
  mkdir Scf && cd Scf || exit
else
  cd Scf
fi

echo '[...]prepare Scf inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Scf

for try_num in $(seq 0 1)
  do
  echo "[...]task Scf round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Scf/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Scf/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 1 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Scf
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Scf failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Scf failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    echo 'Scf success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Scf job done!'
  echo 'Scf success' >> ../stat.log
fi

cd ..

echo '[...]start Band task'
if [ ! -d Band ];then
  mkdir Band && cd Band || exit
else
  cd Band
fi

echo '[...]prepare Band inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Band

# Create ignore.txt marker for Band (ignore_error=True in workflow.json)
touch ignore.txt

for try_num in $(seq 0 1)
  do
  echo "[...]task Band round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Band/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Band/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 1 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Band
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Band failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Band failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    echo 'Band success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Band job done!'
  echo 'Band success' >> ../stat.log
fi

cd ..

echo '[...]start Dos task'
if [ ! -d Dos ];then
  mkdir Dos && cd Dos || exit
else
  cd Dos
fi

echo '[...]prepare Dos inputs.'
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py generate --work_dir . --stage Dos

# Create ignore.txt marker for Dos (ignore_error=True in workflow.json)
touch ignore.txt

for try_num in $(seq 0 1)
  do
  echo "[...]task Dos round: $try_num on 1 node 16 core"
  
  # 在后台启动监控进程（监控详细日志文件）
  if [ -f /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py ]; then
    echo "[...]Starting real-time monitor (monitoring OUT.Dos/running_*.log)"
    (
      # 等待日志文件出现
      for i in {1..30}; do
        LOG_FILE=$(ls -t OUT.Dos/running_*.log 2>/dev/null | head -1)
        if [ -f "$LOG_FILE" ]; then
          tail -f "$LOG_FILE" 2>/dev/null | python -u /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus/monitor.py &
          MONITOR_PID=$!
          echo "[...]Monitor started (PID: $MONITOR_PID)"
          break
        fi
        sleep 1
      done
    ) &
    MONITOR_BG_PID=$!
  fi
  
  # 运行 ABACUS
  yhrun -N 1 -n 16 -p deimos /XYFS01/nscc-gz_pinchen_1/sf_box/abacus-develop-LTSv3.10.0/bin/abacus > running.log 2>&1
  ABACUS_EXIT_CODE=$?
  
  # 停止监控进程
  if [ ! -z "$MONITOR_BG_PID" ]; then
    pkill -P $MONITOR_BG_PID 2>/dev/null
    kill $MONITOR_BG_PID 2>/dev/null
  fi
  
  # 检查计算结果（不管 yhrun 返回值，都检查错误和收敛性）
  echo "[...]checking iteration $try_num result..."
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py errors --work_dir .
  python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py converge --work_dir .
  
  # 如果收敛成功，退出循环
  if [ -f "converge.txt" ]; then
    echo "[...]iteration $try_num: converged successfully!"
    break
  fi
  
  # 未收敛且不是最后一次，准备下一次迭代
  if [ $try_num -lt 1 ]; then
    echo '[...]calculation not done, prepare to next loop'
    python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py update --work_dir . --try_num $try_num --stage Dos
  else
    echo '[...]last iteration completed'
  fi
done

if [ ! -f 'converge.txt' ]; then
  echo '[...]Job failed or not converged'
  # 优先检查是否有真正的错误（error.txt），如果有则必须退出
  if [ -f 'error.txt' ]; then
    echo '[...]Error detected (error.txt exists), cannot continue even with ignore.txt'
    echo 'Dos failed' >> ../stat.log
    exit 1
  elif [ ! -f 'ignore.txt' ]; then
    echo '[...]Not converged and no ignore marker, exiting...'
    echo 'Dos failed' >> ../stat.log
    exit 1
  else
    echo '[...]Not converged but can be ignored (ignore.txt exists), continuing...'
    echo 'Dos success (ignored)' >> ../stat.log
  fi
else
  echo '[...]Dos job done!'
  echo 'Dos success' >> ../stat.log
fi

cd ..


# ===== 汇总结果 =====
python /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/abacus.py summary --root /XYFS01/nscc-gz_pinchen_1/work/dev/abacusflow/work_cal3/hmat_107

echo '[...]ALL STAGES COMPLETED!'
echo 'Workflow completed' >> $stat_log
